# Generated by Django 2.0.1 on 2018-01-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatagory', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('post', models.TextField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='blogs',
        ),
    ]
